services:
  webapp:
    image: ghcr.io/jitsedesmet/demo-construct-query-rewrite:latest
    build:
      context: .
      network: host
    develop:
      watch:
        - action: rebuild
          path: .
    ports:
      - "3000:3000"
